---
- name: Setup basic tools and Docker for user casey
  hosts: all
  become: true  # Run tasks with elevated privileges
  vars:
    user_name: casey  # Variable for the user name

  tasks:
    - name: Install essential packages
      apt:
        name:
          - git
          - tree
          - htop
          - curl
          - docker.io
          - docker-compose
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Create user casey if not exists
      user:
        name: "{{ user_name }}"
        state: present
        shell: /bin/bash

    - name: Add user casey to sudo group
      user:
        name: "{{ user_name }}"
        groups: sudo
        append: yes

    - name: Add user casey to docker group
      user:
        name: "{{ user_name }}"
        groups: docker
        append: yes

    - name: Enable Docker service to start on boot
      systemd:
        name: docker
        enabled: yes
        state: started
