---
version: "3.3"
services:
  ombi:
    image: ghcr.io/linuxserver/ombi:latest
    container_name: ombi
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ombi-config:/config
    ports:
      - "5000:3579"
    depends_on:
    - "mysql_db"

  mysql_db:
    image: "mysql:5.7"
    container_name: ombi_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123 #change your root password here
    volumes:
      -  ombi-mysql:/var/lib/mysql

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - homarr/configs:/app/data/configs
      - homarr/icons:/app/public/icons
      - homarr/data:/data
    ports:
      - '7575:7575'


volumes:
  ombi-config:
  ombi-mysql:
  homarr:
