---
version: "3.3"
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    ports:
      - "3010:3001"
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock



 
  gotify:
    image: gotify/server
    container_name: gotify
    restart: unless-stopped
    ports:
      - 8899:80
    environment:
      - GOTIFY_DEFAULTUSER_PASS=custom
      - TZ='Europe/London'
    volumes:
      - "./gotify_data:/app/data"

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - plexmediaserver-library-config:/config
      - /mnt/usb6tb/media/tv:/data/tv
      - /mnt/usb6tb/media/movies:/data/movies
      - /mnt/usb6tb/media:/data/media
      - /mnt/usb11tb/media:/data2/media
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - JELLYFIN_PublishedServerUrl=https://jellyfin.ms.inthearea.party #optional
    volumes:
      - jellyfin-library-config:/config
      - /mnt/usb6tb/media/tv:/data/tv
      - /mnt/usb6tb/media/movies:/data/movies
      - /mnt/usb6tb/media:/data/media
      - /mnt/usb11tb/media:/data2/media
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
#    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "/opt/appdata/navidrome:/data"
      - "/mnt/usb6tb/media/music:/music:ro"

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8080:8080 #sabnzbd
      - 8081:8081 #qbittorrent
      - 6881:6881 #qb
      - 6881:6881/udp #qb
      - 9117:9117 #jackett

    volumes:
      - gluetun-config:/gluetun
    restart: unless-stopped
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=pia
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=p0790330
      - OPENVPN_PASSWORD=Sba27p23er
      # Wireguard:
      # - WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
      # - WIREGUARD_ADDRESSES=10.64.222.21/32
      # Timezone for accurate log times
      - TZ=Europe/London
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=
      - SERVER_REGIONS=Netherlands

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - jackett-config:/config
      - /mnt/usb6tb/media/downloads:/data/downloads
      - /mnt/usb11tb/media/downloads:/data2/downloads
      - /mnt/usb11tb/media/incomplete:/data2/incomplete-downloads

  #  ports:
 #     - 9117:9117
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - sabnzbd-config:/config
      - /mnt/usb6tb/media/downloads:/data/downloads #optional
      - /mnt/usb6tb/media/incomplete:/data/incomplete-downloads #optional
      - /mnt/usb11tb/media/downloads:/data2/downloads
      - /mnt/usb11tb/media/incomplete:/data2/incomplete-downloads
#    ports:
 #     - 8080:8080
    restart: unless-stopped


  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent-config:/config
      - /mnt/usb6tb/media/downloads:/data/downloads
      - /mnt/usb6tb/media/incomplete:/data/incomplete-downloads
      - /mnt/usb11tb/media/downloads:/data2/downloads
      - /mnt/usb11tb/media/incomplete:/data2/incomplete-downloads

    network_mode: service:gluetun
#    ports:
 #     - 8081:8081
  #    - 6881:6881
   #   - 6881:6881/udp
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - sonarr-config:/config
      - /mnt/usb6tb/media/tv:/data/tv #optional
      - /mnt/usb6tb/media/downloads:/data/downloads #optional
      - /mnt/usb6tb/media/incomplete:/data/incomplete-downloads
      - /mnt/usb11tb/media/tv:/data2/tv
      - /mnt/usb11tb/media/downloads:/data2/downloads
      - /mnt/usb11tb/media/incomplete:/data2/incomplete-downloads

    ports:
      - 8989:8989
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - lidarr-config:/config
      - /mnt/usb6tb/media/music:/data/music #optional
      - /mnt/usb6tb/media/downloads:/data/downloads #optional
      - /mnt/usb6tb/media/incomplete:/data/incomplete-downloads
      - /mnt/usb11tb/media/downloads:/data2/downloads
      - /mnt/usb11tb/media/incomplete:/data2/incomplete-downloads
      - /mnt/usb11tb/media/music:/data2/music
    ports:
      - 8686:8686
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - radarr-config:/config
      - /mnt/usb6tb/media/movies:/data/movies #optional
      - /mnt/usb6tb/media/downloads:/data/downloads #optional
      - /mnt/usb6tb/media/incomplete:/data/incomplete-downloads
      - /mnt/usb11tb/media/movies:/data2/movies
      - /mnt/usb11tb/media/downloads:/data2/downloads
      - /mnt/usb11tb/media/incomplete:/data2/incomplete-downloads

    ports:
      - 7878:7878
    restart: unless-stopped


  readarr:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - readarr-config:/config
      - /mnt/usb6tb/media/books:/data/books #optional
      - /mnt/usb6tb/media/downloads:/data/downloads #optional
      - /mnt/usb6tb/media/incomplete:/data/incomplete-downloads
      - /mnt/usb11tb/media/books:/data2/books
      - /mnt/usb6tb/media/books:/Calibre_Library #this is where your ebooks will end up
      - /mnt/usb11tb/media/downloads:/data2/downloads
      - /mnt/usb11tb/media/incomplete:/data2/incomplete-downloads
    ports:
      - 8787:8787
    restart: unless-stopped
#    networks:
 #     - books

  readarr-audio:
    image: lscr.io/linuxserver/readarr:nightly
    container_name: readarr-audio
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - readarr-audio-config:/config
      - /mnt/usb6tb/media/audiobooks:/data/audiobooks #optional
      - /mnt/usb6tb/media/downloads:/data/downloads #optional
      - /mnt/usb6tb/media/incomplete:/data/incomplete-downloads
      - /mnt/usb11tb/media/audiobooks:/data2/audiobooks
      - /mnt/usb11tb/media/downloads:/data2/downloads
      - /mnt/usb11tb/media/incomplete:/data2/incomplete-downloads

    ports:
      - 8585:8787
    restart: unless-stopped
 #   networks:
#      - books

  ombi:
    image: ghcr.io/linuxserver/ombi:latest
    container_name: ombi
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ombi-config:/config
    ports:
      - "5000:3579"
    depends_on:
    - "mysql_db"

  mysql_db:
    image: "mysql:5.7"
    container_name: ombi_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123 #change your root password here
    volumes:
      -  ombi-mysql:/var/lib/mysql

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /opt/appdata/homarr/configs:/app/data/configs
      - /opt/appdata/homarr/icons:/app/public/icons
      - /opt/appdata/homarr/data:/data
    ports:
      - '7575:7575'


volumes:
  database-data:
    driver: local
  database-config:
    driver: local
  pgadmin:
    driver: local
  qbittorrent-config:
    driver: local
  jackett-config:
    driver: local
  mealie-config:
    driver: local
  mealie-db:
    driver: local
  npm-data:
    driver: local
  letsencrypt:
    driver: local
  duplicati-backups-config:
    driver: local
  plexmediaserver-library-config:
    driver: local
  jellyfin-library-config:
    driver: local
  code-config:
    driver: local
  gluetun-config:
    driver: local
  sabnzbd-config:
    driver: local
  sonarr-config:
    driver: local
  radarr-config:
    driver: local
  lidarr-config:
    driver: local
  readarr-config:
    driver: local
  readarr-audio-config:
    driver: local
  ombi-config:
    driver: local
  ombi-mysql:
    driver: local
  uptime-kuma:
